#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

yum remove -y chrony
yum install -y ntp

echo "server time.northwestern.edu iburst" >> /etc/ntp.conf

systemctl enable ntpd
