#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

yum install -y \
    ansible \
    apr \
    apr-util \
    autoconf \
    automake \
    bison \
    byacc \
    bzip2 \
    collectd \
    cscope \
    ctags \
    curl-devel \
    diffstat \
    doxygen \
    dwz \
    dyninst \
    elfutils \
    emacs-filesystem \
    flex \
    fuse-devel \
    gcc \
    gcc-c++ \
    gcc-gfortran \
    gdb \
    gettext-common-devel \
    gettext-devel \
    indent \
    intltool \
    json-c-devel \
    libdwarf \
    libgfortran \
    libguestfs-tools \
    libquadmath \
    libquadmath-devel \
    libjson-c-dev \
    libstdc++-devel \
    libtool \
    libxml2-devel \
    make \
    neon \
    nscd \
    openssl-devel \
    pakchois \
    patchutils \
    perl-Data-Dumper \
    perl-srpm-macros \
    perl-Test-Harness \
    perl-Thread-Queue \
    perl-XML-Parser \
    puppet \
    python-cinderclient \
    python-cinderclient-doc \
    python-glanceclient \
    python-glanceclient-doc \
    python-heatclient \
    python-heatclient-doc \
    python-keystoneclient \
    python-keystoneclient-doc \
    python-neutronclient \
    python-novaclient \
    python-novaclient-doc \
    python-openstackclient \
    python-swiftclient \
    python-swiftclient-doc \
    python2-gnocchiclient \
    rcs \
    redhat-lsb-core \
    redhat-rpm-config \
    rpm-build \
    rpm-sign \
    subversion \
    subversion-libs \
    swig \
    systemtap \
    systemtap-client \
    systemtap-devel \
    systemtap-runtime \
    unzip

# Missing dependency os-collect-config
yum install -y python2-oslo-log

# Install missing firmware
yum install -y linux-firmware

# NSCD not enabled by default on installation
systemctl enable nscd
