#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -o errexit
set -o nounset
set -o pipefail


#############################################################
# Pre-Installation
#############################################################

NVIDIA_TMP_FOLDER=/root/tmp
mkdir -p $NVIDIA_TMP_FOLDER

# Disabling NOUVEAU doesn't work, but seems harmless
# Disable NOUVEAU http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#runfile-nouveau
# cat > '/etc/modprobe.d/blacklist-nouveau.conf' <<- EOM
# blacklist nouveau
# options nouveau modeset=0
# EOM
# Regenerate kernel
# sudo dracut --force

# Install libraries that are required by CUDA to be fully installed
yum install -y freeglut-devel.x86_64 freeglut.x86_64 libXi-devel.x86_64 \
    mesa-libGL-devel.x86_64 mesa-libGLES.x86_64 mesa-libGLU-devel.x86_64 \
    mesa-libGLw-devel.x86_64 mesa-libGLw.x86_64

#############################################################
# Installation (runfile)
#############################################################

# Install kernel headers and wget
yum install -y kernel-devel-$(uname -r) kernel-headers-$(uname -r) wget dkms

# fence.h has beed renamed to dma-fence.h in the latest kernel, which fails the nvidia installation
# https://lists.centos.org/pipermail/centos/2017-October/166686.html
# Might cause issue
sudo mv /usr/src/kernels/$(uname -r)/include/linux/dma-fence.h /usr/src/kernels/$(uname -r)/include/linux/fence.h

# Get the NVIDIA CUDA Toolkit for Centos
wget -nv http://developer.nvidia.com/compute/cuda/8.0/Prod2/local_installers/cuda_8.0.61_375.26_linux-run
mv cuda_8.0.61_375.26_linux-run cuda_8.0.61_375.26_linux.run

# Install the NVIDIA CUDA Toolkit for Centos
export TMPDIR=$NVIDIA_TMP_FOLDER
sudo sh cuda_8.0.61_375.26_linux.run --samples --toolkit --driver --silent --verbose --tmpdir $NVIDIA_TMP_FOLDER

#############################################################
# Post-Installation
#############################################################

# Mandatory Actions
cat > '/etc/profile.d/cuda.sh' <<- EOM
#!/bin/sh
export PATH=/usr/local/cuda-8.0/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda-8.0/lib64
EOM
chmod +x /etc/profile.d/cuda.sh
echo '/usr/local/cuda-8.0/lib64' > /etc/ld.so.conf.d/nvidia-x86_64.conf
ldconfig

# Compile deviceQuery sample (useful for testing)
DEVICE_QUERY_PATH="/usr/local/cuda-8.0/samples/1_Utilities/deviceQuery"
source /etc/environment
pushd $DEVICE_QUERY_PATH
make
popd

# Generate startup script that load information from NVIDIA device query. This
# forces NVIDIA devices to be ready when booting a GPU node.
cat > /etc/load_nvidia_info <<- EOM
#!/bin/bash
DEVICE_QUERY_PATH="$DEVICE_QUERY_PATH"
OUTPUT_FILE_PATH="/opt/nvidia.txt"

pushd \$DEVICE_QUERY_PATH
./deviceQuery > \$OUTPUT_FILE_PATH
chmod 777 \$OUTPUT_FILE_PATH
popd
EOM

# Add startup script that load information from NVIDIA device query
chmod a+x /etc/load_nvidia_info
echo "/etc/load_nvidia_info" >> /etc/rc.local

# Ensure that /etc/rc.local is executable
chmod +x /etc/rc.local

#############################################################
# Cleaning
#############################################################

# Clean the tmp folder used by CUDA
rm -rf $NVIDIA_TMP_FOLDER

# Remove the CUDA Installer
rm -f cuda_8.0.61_375.26_linux.run

exit 0
