#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
#set -o nounset
set -o errexit
set -o pipefail

#############################################################
# Pre-Installation
#############################################################

SCRIPTDIR=$(dirname $0)
FPGA_INSTALL_FOLDER=/root/tmp
mkdir -p $FPGA_INSTALL_FOLDER
sudo cp -r $SCRIPTDIR/fpga $FPGA_INSTALL_FOLDER
PKG_SOURCE=$FPGA_INSTALL_FOLDER/fpga

QUARTUS_ROOTDIR=/etc/intelFPGA_pro/17.1

#############################################################
# Installation
#############################################################

yum install -y libpng12 udev usbutils
ln -s /lib64/libudev.so.1 /lib64/libudev.so.0

cd $PKG_SOURCE
./AOCLProSetup-17.1.0.240-linux.run --mode unattended --installdir $QUARTUS_ROOTDIR --accept_eula 1

mkdir -p /etc/OpenCL/vendors
cp $QUARTUS_ROOTDIR/hld/Altera.icd /etc/OpenCL/vendors << EOF
y
EOF

tar xvfz $PKG_SOURCE/de5a_net_e1.tar.gz -C $QUARTUS_ROOTDIR/hld/board

cp $PKG_SOURCE/aoc-env-de5anet.sh /etc/profile.d/
source /etc/profile.d/aoc-env-de5anet.sh

# Fix bug in aocl install in Intel FPGA SDK for OpenCL17.1
# https://www.intel.com/content/www/us/en/programmable/support/support-resources/knowledge-base/embedded/2017/why-does-aocl-install-and-aocl-uninstall-fail-in-intel-fpga-sdk-.html
sed -i '110s/isWindowsOS()/acl::Env::is_windows()/' /etc/intelFPGA_pro/17.1/hld/share/lib/perl/acl/Command.pm
sed -i '111s/mysystem_full({}, @cmd);/system(@cmd);/' /etc/intelFPGA_pro/17.1/hld/share/lib/perl/acl/Command.pm

# Build kernel module
aocl install << EOF
y
EOF

# Add startup script 
chmod a+x /etc/profile.d/aoc-env-de5anet.sh
echo "/etc/profile.d/aoc-env-de5anet.sh" >> /etc/rc.local

# Ensure that /etc/rc.local is executable
chmod +x /etc/rc.local

#############################################################
# Cleaning
#############################################################

sudo rm -r $PKG_SOURCE

exit 0
