#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

mkdir -p $TMP_BUILD_DIR/opt/chameleon
echo $DIB_CC_PROVENANCE # debugging
echo $DIB_CC_PROVENANCE | base64 -d | python -mjson.tool > $TMP_BUILD_DIR/opt/chameleon/provenance.json
